import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class AppLocalization {
  final Locale locale;
  AppLocalization(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Enterprise POS',
      'company_title': 'Project-Enterprise-E-Commerce',
      'company_subtitle': 'Continue to your enterprise workspace',
      'login': 'Sign In',
      'username': 'Username',
      'enter_username': 'Enter your username',
      'email': 'Email Address',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'remember_me': 'Remember Me',
      'remember_device': 'Remember Device',
      'forgot_password': 'Forgot Password?',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Enterprise Mobile ERP & POS Terminal',
      'sign_in_to_terminal': 'SIGN IN TO TERMINAL',
      'biometric_login': 'Biometric Login',
      'qr_login': 'Scan QR Login',
      'guest_demo': 'Guest Demo',
      'signing_in': 'Signing In...',
      'login_success': 'Authenticated Successfully!',
      'username_required': 'Username is required',
      'username_too_short': 'Username must be at least 3 characters',
      'password_required': 'Password is required',
      'password_too_short': 'Password must be at least 6 characters',
      'forgot_password_sheet_title': 'Reset Account Password',
      'phone_or_username': 'Username or Phone Number',
      'send_otp': 'SEND VERIFICATION OTP',
      'enter_otp': 'Enter 6-Digit OTP',
      'new_password': 'New Password',
      'reset_success': 'Password reset successfully!',
      'contact_admin': 'Contact Administrator',
      'version': 'v1.0.0 (Build 100)',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms & Conditions',
      'copyright': '© 2026 Enterprise E-Commerce & POS System. All Rights Reserved.',
      'wrong_credentials': 'Invalid username or password credentials.',
      'account_locked': 'Account has been locked due to multiple failed attempts. Contact admin.',
      'user_disabled': 'User account is disabled. Contact your supervisor.',
      'password_expired': 'Password has expired. Please reset your password.',
      'too_many_attempts': 'Too many attempts. Please try again in 60 seconds.',
      'server_offline': 'Enterprise server is unreachable. Check network or server state.',
      'session_expired': 'Session expired. Please re-authenticate.',
      'encrypted_security': '🔒 256-Bit Encrypted',
      'realtime_sync': '⚡ Realtime POS Sync',
      'multi_branch': '🌐 Multi-Branch ERP',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'theme_system': 'System Auto',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'good_night': 'Good Night',
      'administrator': 'Senior Administrator',
      'kpi_summary': 'Key Performance Indicators',
      'sales_trend': 'Revenue & Sales Analytics',
      'express_actions': 'Express Quick Actions',
      'erp_modules': 'Enterprise Module Catalog',
      'realtime_activities': 'Realtime Operational Feed',
      'recent_sales_table': 'Recent POS Transactions',
      'inventory_risk_alerts': 'Inventory Risk & Expiry Center',
      'hr_attendance_summary': 'HR & Staff Attendance Summary',
      'top_performers': 'Top Performers & VIP Customers',
      'tasks_weather_currency': 'Operations, Delivery & Rates',
      'system_health': 'Infrastructure & Gateway Health',
      'home': 'Home',
      'pos': 'POS Terminal',
      'products': 'Products',
      'inventory': 'Inventory',
      'purchases': 'Purchases',
      'sales': 'Sales',
      'reports': 'Reports',
      'finance': 'Finance',
      'crm': 'CRM & Customers',
      'employees': 'Employees',
      'settings': 'Settings',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'todays_sales': 'Today\'s Sales',
      'todays_purchase': 'Today\'s Purchase',
      'revenue': 'Revenue',
      'net_profit': 'Net Profit',
      'recent_orders': 'Recent Orders',
      'low_stock': 'Low Stock Alert',
      'checkout': 'Checkout',
      'cash': 'Cash',
      'khqr': 'KHQR Bakong',
      'card': 'Credit Card',
      'pay_now': 'Pay Now',
      'print_receipt': 'Print Receipt',
      'scan_qr': 'Scan QR Code',
      'offline_mode': 'Offline Mode (Auto Sync)',
    },
    'km': {
      'app_title': 'ប្រព័ន្ធលក់សហគ្រាស',
      'company_title': 'Project-Enterprise-E-Commerce',
      'company_subtitle': 'បន្តទៅកាន់កន្លែងធ្វើការសហគ្រាសរបស់អ្នក',
      'login': 'ចូលប្រព័ន្ធ',
      'username': 'ឈ្មោះអ្នកប្រើប្រាស់',
      'enter_username': 'បញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
      'email': 'អ៊ីមែល',
      'password': 'ពាក្យសម្ងាត់',
      'enter_password': 'បញ្ចូលពាក្យសម្ងាត់',
      'remember_me': 'ចងចាំខ្ញុំ',
      'remember_device': 'ចងចាំឧបករណ៍នេះ',
      'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
      'welcome_back': 'ស្វាគមន៍ការត្រឡប់មកវិញ',
      'login_subtitle': 'ប្រព័ន្ធគ្រប់គ្រងសហគ្រាស និង POS',
      'sign_in_to_terminal': 'ចូលទៅកាន់ប្រព័ន្ធ',
      'biometric_login': 'ស្កែនក្រយ៉ៅដៃ / ទម្រង់មុខ',
      'qr_login': 'ស្កែន QR ចូលប្រព័ន្ធ',
      'guest_demo': 'គណនីសាកល្បង',
      'signing_in': 'កំពុងផ្ទៀងផ្ទាត់...',
      'login_success': 'ចូលប្រព័ន្ធជោគជ័យ!',
      'username_required': 'សូមបញ្ចូលឈ្មោះអ្នកប្រើប្រាស់',
      'username_too_short': 'ឈ្មោះអ្នកប្រើប្រាស់យ៉ាងហោចណាស់ ៣ តួ',
      'password_required': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_too_short': 'ពាក្យសម្ងាត់យ៉ាងហោចណាស់ ៦ តួ',
      'forgot_password_sheet_title': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
      'phone_or_username': 'ឈ្មោះអ្នកប្រើប្រាស់ ឬលេខទូរស័ព្ទ',
      'send_otp': 'ផ្ញើសូដលេខ OTP',
      'enter_otp': 'បញ្ចូលកូដ OTP ៦ ខ្ទង់',
      'new_password': 'ពាក្យសម្ងាត់ថ្មី',
      'reset_success': 'កំណត់ពាក្យសម្ងាត់ជោគជ័យ!',
      'contact_admin': 'ទាក់ទងអ្នកគ្រប់គ្រង',
      'version': 'កំណែ v1.0.0 (Build 100)',
      'privacy_policy': 'គោលការណ៍ឯកជនភាព',
      'terms_of_service': 'លក្ខខណ្ឌប្រើប្រាស់',
      'copyright': '© 2026 Enterprise E-Commerce & POS System. រក្សាសិទ្ធិគ្រប់យ៉ាង។',
      'wrong_credentials': 'ឈ្មោះអ្នកប្រើប្រាស់ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។',
      'account_locked': 'គណនីត្រូវបានចាក់សោ។ សូមទាក់ទងអ្នកគ្រប់គ្រង។',
      'user_disabled': 'គណនីត្រូវបានផ្អាកដំណើរការ។',
      'password_expired': 'ពាក្យសម្ងាត់ផុតកំណត់។ សូមផ្លាស់ប្តូរពាក្យសម្ងាត់។',
      'too_many_attempts': 'ព្យាយាមច្រើនដងពេក។ សូមរង់ចាំ ៦០ វិនាទី។',
      'server_offline': 'ម៉ាស៊ីនបម្រើសហគ្រាសមិនអាចតភ្ជាប់បានទេ។',
      'session_expired': 'សម័យប្រជុំផុតកំណត់។ សូមចូលប្រព័ន្ធម្តងទៀត។',
      'encrypted_security': '🔒 សុវត្ថិភាព 256-Bit',
      'realtime_sync': '⚡ សមកាលកម្ម POS ភ្លាមៗ',
      'multi_branch': '🌐 ERP ច្រើនសាខា',
      'theme_light': 'ពន្លឺ',
      'theme_dark': 'ងងឹត',
      'theme_system': 'តាមប្រព័ន្ធ',
      'home': 'ទំព័រដើម',
      'pos': 'កន្លែងលក់ (POS)',
      'products': 'ទំនិញ',
      'inventory': 'ស្តុក',
      'purchases': 'ការទិញចូល',
      'sales': 'ការលក់',
      'reports': 'របាយការណ៍',
      'finance': 'ហិរញ្ញវត្ថុ',
      'crm': 'អតិថិជន',
      'employees': 'បុគ្គលិក',
      'settings': 'ការកំណត់',
      'profile': 'គណនី',
      'notifications': 'ការជូនដំណឹង',
      'logout': 'ចាកចេញ',
      'todays_sales': 'ការលក់ថ្ងៃនេះ',
      'todays_purchase': 'ការទិញថ្ងៃនេះ',
      'revenue': 'ចំណូលសរុប',
      'net_profit': 'ប្រាក់ចំណេញសុទ្ធ',
      'recent_orders': 'ការបញ្ជាទិញថ្មីៗ',
      'low_stock': 'ទំនិញជិតអស់ពីស្តុក',
      'checkout': 'គិតប្រាក់',
      'cash': 'ប្រាក់សុទ្ធ',
      'khqr': 'KHQR បាគង',
      'card': 'កាតធនាគារ',
      'pay_now': 'បង់ប្រាក់ឥឡូវនេះ',
      'print_receipt': 'បោះពុម្ពវិក្កយបត្រ',
      'scan_qr': 'ស្កែន QR',
      'offline_mode': 'របៀបអូហ្វឡាញ (សមកាលកម្មស្វ័យប្រវត្តិ)',
    },
    'th': {
      'app_title': 'ระบบขายหน้าร้านองค์กร',
      'company_title': 'Project-Enterprise-E-Commerce',
      'company_subtitle': 'เข้าสู่พื้นที่ทำงานองค์กรของคุณ',
      'login': 'เข้าสู่ระบบ',
      'username': 'ชื่อผู้ใช้',
      'enter_username': 'กรอกชื่อผู้ใช้',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'enter_password': 'กรอกรหัสผ่าน',
      'remember_me': 'จดจำฉัน',
      'remember_device': 'จำอุปกรณ์นี้',
      'forgot_password': 'ลืมรหัสผ่าน?',
      'welcome_back': 'ยินดีต้อนรับกลับ',
      'login_subtitle': 'ระบบจัดการองค์กรและ POS',
      'sign_in_to_terminal': 'เข้าสู่ระบบเทอร์มินัล',
      'biometric_login': 'สแกนชีวมิติ',
      'qr_login': 'สแกน QR เข้าสู่ระบบ',
      'guest_demo': 'ทดลองใช้งาน',
      'signing_in': 'กำลังเข้าสู่ระบบ...',
      'login_success': 'เข้าสู่ระบบสำเร็จ!',
      'username_required': 'กรุณากรอกชื่อผู้ใช้',
      'username_too_short': 'ชื่อผู้ใช้ต้องมีอย่างน้อย 3 ตัวอักษร',
      'password_required': 'กรุณากรอกรหัสผ่าน',
      'password_too_short': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
      'forgot_password_sheet_title': 'ตั้งรหัสผ่านใหม่',
      'phone_or_username': 'ชื่อผู้ใช้หรือเบอร์โทรศัพท์',
      'send_otp': 'ส่งรหัส OTP',
      'enter_otp': 'กรอกรหัส OTP 6 หลัก',
      'new_password': 'รหัสผ่านใหม่',
      'reset_success': 'ตั้งรหัสผ่านใหม่เรียบร้อยแล้ว!',
      'contact_admin': 'ติดต่อผู้ดูแลระบบ',
      'version': 'เวอร์ชัน v1.0.0 (Build 100)',
      'privacy_policy': 'นโยบายความเป็นส่วนตัว',
      'terms_of_service': 'ข้อตกลงและเงื่อนไข',
      'copyright': '© 2026 Enterprise E-Commerce & POS System. สงวนลิขสิทธิ์.',
      'wrong_credentials': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
      'account_locked': 'บัญชีถูกระงับ กรุณาติดต่อผู้ดูแลระบบ',
      'user_disabled': 'บัญชีผู้ใช้นี้ถูกปิดใช้งาน',
      'password_expired': 'รหัสผ่านหมดอายุ กรุณาตั้งใหม่',
      'too_many_attempts': 'พยายามบ่อยเกินไป กรุณารอ 60 วินาที',
      'server_offline': 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้',
      'session_expired': 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่',
      'encrypted_security': '🔒 ปลอดภัยระดับ 256-Bit',
      'realtime_sync': '⚡ ซิงค์ POS เรียลไทม์',
      'multi_branch': '🌐 ERP รองรับหลายสาขา',
      'theme_light': 'โหมดสว่าง',
      'theme_dark': 'โหมดมืด',
      'theme_system': 'ตามระบบ',
      'home': 'หน้าแรก',
      'pos': 'ระบบขาย POS',
      'products': 'สินค้า',
      'inventory': 'คลังสินค้า',
      'purchases': 'การสั่งซื้อ',
      'sales': 'ยอดขาย',
      'reports': 'รายงาน',
      'finance': 'การเงิน',
      'crm': 'ลูกค้า',
      'employees': 'พนักงาน',
      'settings': 'ตั้งค่า',
      'profile': 'โปรไฟล์',
      'notifications': 'การแจ้งเตือน',
      'logout': 'ออกจากระบบ',
      'todays_sales': 'ยอดขายวันนี้',
      'todays_purchase': 'ยอดซื้อวันนี้',
      'revenue': 'รายได้รวม',
      'net_profit': 'กำไรสุทธิ',
      'recent_orders': 'รายการล่าสุด',
      'low_stock': 'สินค้าใกล้หมด',
      'checkout': 'ชำระเงิน',
      'cash': 'เงินสด',
      'khqr': 'KHQR สแกน',
      'card': 'บัตรเครดิต',
      'pay_now': 'ชำระเงินทันที',
      'print_receipt': 'พิมพ์ใบเสร็จ',
      'scan_qr': 'สแกน QR',
      'offline_mode': 'โหมดออฟไลน์',
    },
    'vi': {
      'app_title': 'Hệ Thống Bán Hàng Doanh Nghiệp',
      'company_title': 'Project-Enterprise-E-Commerce',
      'company_subtitle': 'Tiếp tục truy cập không gian làm việc doanh nghiệp',
      'login': 'Đăng Nhập',
      'username': 'Tên Đăng Nhập',
      'enter_username': 'Nhập tên đăng nhập',
      'email': 'Email',
      'password': 'Mật Khẩu',
      'enter_password': 'Nhập mật khẩu',
      'remember_me': 'Ghi Nhớ',
      'remember_device': 'Ghi Nhớ Thiết Bị',
      'forgot_password': 'Quên Mật Khẩu?',
      'welcome_back': 'Chào Mừng Trở Lại',
      'login_subtitle': 'Hệ Thống Quản Trị ERP & POS Mobile',
      'sign_in_to_terminal': 'ĐĂNG NHẬP VÀO THIẾT BỊ',
      'biometric_login': 'Đăng Nhập Sinh Trắc Học',
      'qr_login': 'Quét Mã QR Đăng Nhập',
      'guest_demo': 'Dùng Thử Demo',
      'signing_in': 'Đang xác thực...',
      'login_success': 'Đăng nhập thành công!',
      'username_required': 'Vui lòng nhập tên đăng nhập',
      'username_too_short': 'Tên đăng nhập tối thiểu 3 ký tự',
      'password_required': 'Vui lòng nhập mật khẩu',
      'password_too_short': 'Mật khẩu phải có ít nhất 6 ký tự',
      'forgot_password_sheet_title': 'Đặt Lại Mật Khẩu',
      'phone_or_username': 'Tên đăng nhập hoặc Số điện thoại',
      'send_otp': 'GỬI MÃ OTP XÁC NHẬN',
      'enter_otp': 'Nhập Mã OTP 6 Chữ Số',
      'new_password': 'Mật Khẩu Mới',
      'reset_success': 'Đặt lại mật khẩu thành công!',
      'contact_admin': 'Liên Hệ Quản Trị Viên',
      'version': 'Phiên bản v1.0.0 (Build 100)',
      'privacy_policy': 'Chính Sách Bảo Mật',
      'terms_of_service': 'Điều Khoản Sử Dụng',
      'copyright': '© 2026 Enterprise E-Commerce & POS System. Bảo lưu mọi quyền.',
      'wrong_credentials': 'Tên đăng nhập hoặc mật khẩu không chính xác.',
      'account_locked': 'Tài khoản đã bị khóa. Vui lòng liên hệ quản trị viên.',
      'user_disabled': 'Tài khoản của bạn đã bị vô hiệu hóa.',
      'password_expired': 'Mật khẩu đã hết hạn. Vui lòng đổi mật khẩu.',
      'too_many_attempts': 'Thử quá nhiều lần. Vui lòng đợi 60 giây.',
      'server_offline': 'Không thể kết nối với máy chủ doanh nghiệp.',
      'session_expired': 'Phiên làm việc hết hạn. Vui lòng đăng nhập lại.',
      'encrypted_security': '🔒 Mã Hóa 256-Bit',
      'realtime_sync': '⚡ Đồng Bộ POS Thời Gian Thực',
      'multi_branch': '🌐 ERP Đa Chi Nhánh',
      'theme_light': 'Giao Diện Sáng',
      'theme_dark': 'Giao Diện Tối',
      'theme_system': 'Theo Hệ Thống',
      'home': 'Trang Chủ',
      'pos': 'Điểm Bán Hàng',
      'products': 'Sản Phẩm',
      'inventory': 'Kho Hàng',
      'purchases': 'Nhập Hàng',
      'sales': 'Bán Hàng',
      'reports': 'Báo Cáo',
      'finance': 'Tài Chính',
      'crm': 'Khách Hàng',
      'employees': 'Nhân Viên',
      'settings': 'Cài Đặt',
      'profile': 'Hồ Sơ',
      'notifications': 'Thông Báo',
      'logout': 'Đăng Xuất',
      'todays_sales': 'Doanh Số Hôm Nay',
      'todays_purchase': 'Nhập Hàng Hôm Nay',
      'revenue': 'Doanh Thu',
      'net_profit': 'Lợi Nhuận Ròng',
      'recent_orders': 'Đơn Hàng Gần Đây',
      'low_stock': 'Cảnh Báo Tồn Kho',
      'checkout': 'Thanh Toán',
      'cash': 'Tiền Mặt',
      'khqr': 'KHQR Quét',
      'card': 'Thẻ Tín Dụng',
      'pay_now': 'Thanh Toán Ngay',
      'print_receipt': 'In Hóa Đơn',
      'scan_qr': 'Quét Mã QR',
      'offline_mode': 'Chế Độ Ngoại Tuyến',
    },
    'zh': {
      'app_title': '企业级 POS 系统',
      'company_title': 'Project-Enterprise-E-Commerce',
      'company_subtitle': '继续访问您的企业工作空间',
      'login': '登录',
      'username': '用户名',
      'enter_username': '请输入用户名',
      'email': '电子邮箱',
      'password': '密码',
      'enter_password': '请输入密码',
      'remember_me': '记住我',
      'remember_device': '记住此设备',
      'forgot_password': '忘记密码？',
      'welcome_back': '欢迎回来',
      'login_subtitle': '企业级 ERP 与 POS 收银终端',
      'sign_in_to_terminal': '登录终端',
      'biometric_login': '生物识别登录',
      'qr_login': '扫码登录',
      'guest_demo': '演示账号',
      'signing_in': '正在验证...',
      'login_success': '登录成功！',
      'username_required': '请输入用户名',
      'username_too_short': '用户名至少 3 个字符',
      'password_required': '请输入密码',
      'password_too_short': '密码长度不能少于 6 位',
      'forgot_password_sheet_title': '重置账号密码',
      'phone_or_username': '用户名或手机号码',
      'send_otp': '发送验证码 OTP',
      'enter_otp': '输入 6 位数验证码',
      'new_password': '新密码',
      'reset_success': '密码重置成功！',
      'contact_admin': '联系系统管理员',
      'version': '版本 v1.0.0 (Build 100)',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'copyright': '© 2026 Enterprise E-Commerce & POS System. 保留所有权利。',
      'wrong_credentials': '用户名或密码错误。',
      'account_locked': '账号已被锁定，请联系管理员。',
      'user_disabled': '该用户账号已被停用。',
      'password_expired': '密码已过期，请重置密码。',
      'too_many_attempts': '尝试次数过多，请 60 秒后再试。',
      'server_offline': '无法连接到企业服务器。',
      'session_expired': '会话已过期，请重新登录。',
      'encrypted_security': '🔒 256-Bit 加密安全',
      'realtime_sync': '⚡ 实时 POS 数据同步',
      'multi_branch': '🌐 多门店 ERP 架构',
      'theme_light': '浅色模式',
      'theme_dark': '深色模式',
      'theme_system': '跟随系统',
      'home': '首页',
      'pos': '收银终端',
      'products': '商品管理',
      'inventory': '库存管理',
      'purchases': '采购管理',
      'sales': '销售管理',
      'reports': '报表分析',
      'finance': '财务管理',
      'crm': '客户管理',
      'employees': '员工管理',
      'settings': '系统设置',
      'profile': '个人中心',
      'notifications': '消息通知',
      'logout': '退出登录',
      'todays_sales': '今日销售额',
      'todays_purchase': '今日采购额',
      'revenue': '总营业额',
      'net_profit': '净利润',
      'recent_orders': '最新订单',
      'low_stock': '库存预警',
      'checkout': '结账',
      'cash': '现金',
      'khqr': 'KHQR 扫码',
      'card': '信用卡',
      'pay_now': '立即支付',
      'print_receipt': '打印小票',
      'scan_qr': '扫二维码',
      'offline_mode': '离线模式 (自动同步)',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

final localeProvider = StateProvider<Locale>((ref) => const Locale('en'));

extension LocalizationHelper on BuildContext {
  String tr(WidgetRef ref, String key) {
    final loc = ref.watch(localeProvider);
    return AppLocalization(loc).translate(key);
  }
}
