import type { BannerPreset } from '../types/banner'

export const CAMBODIA_BANNER_PRESETS: BannerPreset[] = [
  {
    id: 'kny_hero_banner',
    nameKm: '🌸 មហោស្រពចូលឆ្នាំខ្មែរ (Khmer New Year Hero Banner)',
    nameEn: 'Khmer New Year Grand Festive Hero Banner',
    badge: 'KNY 2026',
    category: 'Cambodia Festival',
    placement: 'hero',
    channel_scope: 'all',
    descriptionKm: 'ផ្ទាំងបដាធំក្បាលទំព័រអបអរបុណ្យចូលឆ្នាំថ្មីប្រពៃណីជាតិខ្មែរ បញ្ចុះតម្លៃរហូតដល់ ៥០%',
    descriptionEn: 'Full-width storefront hero carousel banner celebrating Khmer New Year with 50% discount offers',
    titleKm: '🌸 មហោស្រពចូលឆ្នាំខ្មែរ បញ្ចុះតម្លៃពិសេស ៥០%',
    titleEn: 'Khmer New Year Mega Celebration — Up to 50% OFF',
    subtitleKm: 'ការបញ្ចុះតម្លៃដ៏អស្ចារ្យលើទំនិញពេញនិយម និងគ្រឿងអេឡិចត្រូនិច ព្រមទាំងការទូទាត់ Bakong KHQR',
    subtitleEn: 'Exclusive festive savings on premium gadgets, fashion, and local collections with instant KHQR cashback.',
    buttonTextKm: 'ទិញឥឡូវនេះ (Shop Now)',
    buttonTextEn: 'Explore Deals',
    discount_tag: '50% OFF',
    theme_gradient: 'from-amber-500/80 via-rose-500/80 to-purple-600/90',
    defaultImage: '/api/v1/storage/banners/banner_hero_1.webp',
    target_type: 'flash_sale',
  },
  {
    id: 'pchum_ben_banner',
    nameKm: '🏮 ពិធីបុណ្យភ្ជុំបិណ្ឌ (Pchum Ben Blessings & Deals)',
    nameEn: 'Pchum Ben Festive Gift Sets & Family Deals',
    badge: 'PCHUM BEN',
    category: 'Cambodia Festival',
    placement: 'hero',
    channel_scope: 'all',
    descriptionKm: 'ផ្ទាំងបដាកាដូ និងគ្រឿងប្រើប្រាស់សម្រាប់រដូវកាលភ្ជុំបិណ្ឌ និងការជួបជុំគ្រួសារ',
    descriptionEn: 'Family festive banner featuring holiday gifts, hampers, and electronics with instant delivery',
    titleKm: '🏮 ប្រូម៉ូសិនរដូវកាលភ្ជុំបិណ្ឌ កាដូ និងឈុតសន្សំសំចៃ',
    titleEn: 'Pchum Ben Season Specials & Family Gift Hampers',
    subtitleKm: 'ទិញកាដូជូនមនុស្សជាទីស្រលាញ់ជាមួយនឹងការបញ្ចុះតម្លៃ ៣៥% និងដឹកជញ្ជូនឥតគិតថ្លៃ',
    subtitleEn: 'Thoughtful holiday gift packages and essentials with 35% discount and free nationwide dispatch.',
    buttonTextKm: 'មើលកាតាឡុក (View Offers)',
    buttonTextEn: 'View Holiday Sets',
    discount_tag: '35% OFF',
    theme_gradient: 'from-amber-600/80 via-orange-500/80 to-yellow-600/90',
    defaultImage: '/api/v1/storage/banners/banner_hero_2.webp',
    target_type: 'category',
  },
  {
    id: 'water_festival_banner',
    nameKm: '🚣 ព្រះរាជពិធីបុណ្យអុំទូក (Water Festival Regatta Splash)',
    nameEn: 'Water Festival Lightning Deals 40% OFF',
    badge: 'BON OM TOUK',
    category: 'Cambodia Festival',
    placement: 'hero',
    channel_scope: 'all',
    descriptionKm: 'ផ្ទាំងបដាអបអរព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ',
    descriptionEn: 'Water Festival regatta celebrations hero banner with fast flash discount vouchers',
    titleKm: '🚣 ព្រះរាជពិធីបុណ្យអុំទូក បញ្ចុះតម្លៃភ្លាមៗ ៤០%',
    titleEn: 'Water Festival Mega Regatta Specials 40% OFF',
    subtitleKm: 'អបអរសាទរពិធីបុណ្យអុំទូក ជាមួយនឹងការបញ្ចុះតម្លៃពិសេសលើគ្រប់ទំនិញ',
    subtitleEn: 'Celebrate the Water Festival with massive price drops and instant digital voucher rewards.',
    buttonTextKm: 'ទទួលប្រូម៉ូសិន',
    buttonTextEn: 'Claim Promotion',
    discount_tag: '40% OFF',
    theme_gradient: 'from-cyan-600/80 via-blue-600/80 to-indigo-700/90',
    defaultImage: '/api/v1/storage/banners/banner_hero_3.webp',
    target_type: 'coupon',
  },
  {
    id: 'singles_day_1111',
    nameKm: '🛍️ មហាព្រឹត្តិការណ៍ 11.11 (11.11 Midnight Hero 60% OFF)',
    nameEn: '11.11 Global Shopping Festival Midnight Hero',
    badge: '11.11 MEGA',
    category: 'Global Shopping Festival',
    placement: 'hero',
    channel_scope: 'all',
    descriptionKm: 'មហាព្រឹត្តិការណ៍ទិញទំនិញ 11.11 ទូទាំងពិភពលោក បញ្ចុះតម្លៃរហូតដល់ ៦០%',
    descriptionEn: 'The biggest global shopping event hero banner featuring 60% off countdown deals',
    titleKm: '⚡ 11.11 មហាព្រឹត្តិការណ៍ទិញទំនិញធំបំផុតប្រចាំឆ្នាំ',
    titleEn: '11.11 Global Mega Shopping Day — Up to 60% OFF',
    subtitleKm: 'ចាប់ផ្ដើមពីម៉ោង 00:00 យប់ ទំនិញម៉ាកល្បីៗរាប់ពាន់មុខបញ្ចុះតម្លៃរហូតដល់ ៦០%',
    subtitleEn: 'Midnight drops on genuine electronics, smart wearables, and top lifestyle brands.',
    buttonTextKm: 'ទិញឥឡូវនេះ (Shop Now)',
    buttonTextEn: 'Shop Midnight Deals',
    discount_tag: '60% OFF',
    theme_gradient: 'from-rose-600/90 via-purple-600/80 to-blue-700/90',
    defaultImage: '/api/v1/storage/banners/banner_hero_4.webp',
    target_type: 'flash_sale',
  },
  {
    id: 'pos_cfd_checkout_banner',
    nameKm: '📟 POS Customer-Facing Display (CFD Upsell Banner)',
    nameEn: 'POS Customer Screen Dual Display Promotion',
    badge: 'POS CFD',
    category: 'POS Retail Hardware',
    placement: 'pos_cfd',
    channel_scope: 'pos_cfd',
    descriptionKm: 'ផ្ទាំងបដាសម្រាប់បង្ហាញលើអេក្រង់ទី ២ បែរទៅរកភ្ញៀវនៅបញ្ជរបង់ប្រាក់ POS (ស្កេន KHQR / បញ្ចុះតម្លៃ)',
    descriptionEn: 'Dual-screen customer display banner prompting KHQR scan discounts and instant checkout upsell',
    titleKm: '🇰🇭 ស្កេនទូទាត់តាម Bakong KHQR បញ្ចុះតម្លៃ ៥% ភ្លាមៗ',
    titleEn: 'Scan & Pay with Bakong KHQR for Instant 5% OFF',
    subtitleKm: 'បង្ហាញ QR Code លើអេក្រង់ដើម្បីទទួលបានការបញ្ចុះតម្លៃភ្លាមៗនៅបញ្ជរគិតលុយ',
    subtitleEn: 'Scan your mobile banking app at checkout counter to claim instant cashier savings.',
    buttonTextKm: 'ស្កេនទូទាត់ (Scan QR)',
    buttonTextEn: 'Scan to Pay',
    discount_tag: 'KHQR 5%',
    theme_gradient: 'from-red-600/90 via-rose-600/80 to-amber-600/80',
    defaultImage: '/api/v1/storage/banners/banner_spotlight_1.webp',
    target_type: 'coupon',
  },
  {
    id: 'mobile_app_splash',
    nameKm: '📱 Mobile App Welcome Splash Banner',
    nameEn: 'Mobile App Launch Splash & First Order Offer',
    badge: 'APP EXCLUSIVE',
    category: 'Mobile App',
    placement: 'app_splash',
    channel_scope: 'mobile_app',
    descriptionKm: 'ផ្ទាំងបដាលោតស្វាគមន៍ពេលបើក Mobile App ដំបូង ផ្ដល់ជូនគូប៉ុង $10 សម្រាប់ Order ដំបូង',
    descriptionEn: 'Full-screen mobile app onboarding splash banner with $10 first-order voucher promo code',
    titleKm: '🎉 ទាញយក App ទទួលបានគូប៉ុង $10.00 ភ្លាមៗ',
    titleEn: 'Welcome to OptaPOS App — Get $10 Voucher',
    subtitleKm: 'ប្រើកូដ APP10 លើការបញ្ជាទិញលើកដំបូងតាមទូរស័ព្ទដៃ',
    subtitleEn: 'Use code APP10 at mobile checkout for instant $10 discount on your first order.',
    buttonTextKm: 'ទទួលកូដឥឡូវនេះ',
    buttonTextEn: 'Claim $10 Code',
    discount_tag: '$10 OFF',
    theme_gradient: 'from-indigo-600/90 via-purple-600/80 to-pink-600/80',
    defaultImage: '/api/v1/storage/banners/banner_hero_5.webp',
    target_type: 'coupon',
  },
  {
    id: 'payday_weekend_deals',
    nameKm: '💳 ចុងសប្តាហ៍បើកប្រាក់ខែ (Payday Weekend 30% OFF)',
    nameEn: 'Payday Weekend Mega Deals 30% OFF',
    badge: 'PAYDAY SPECIAL',
    category: 'Monthly Routine',
    placement: 'hero',
    channel_scope: 'all',
    descriptionKm: 'ផ្ទាំងបដាប្រូម៉ូសិនរៀងរាល់ចុងខែសម្រាប់ជំរុញការលក់លើទំនិញប្រណិត',
    descriptionEn: 'Month-end salary booster hero banner highlighting exclusive weekend discounts',
    titleKm: '💳 ចុងសប្តាហ៍បើកប្រាក់ខែ បញ្ចុះតម្លៃ ៣០% គ្រប់ទំនិញ',
    titleEn: 'Payday Weekend Clearance — Flat 30% Discount',
    subtitleKm: 'រីករាយជាមួយការដើរទិញទំនិញចុងសប្តាហ៍ជាមួយនឹងតម្លៃពិសេសបំផុត',
    subtitleEn: 'Treat yourself with our curated weekend tech and lifestyle selection at flat 30% OFF.',
    buttonTextKm: 'ទិញឥឡូវនេះ',
    buttonTextEn: 'Shop Payday Deals',
    discount_tag: '30% OFF',
    theme_gradient: 'from-emerald-600/90 via-teal-600/80 to-blue-700/80',
    defaultImage: '/api/v1/storage/banners/banner_hero_6.webp',
    target_type: 'flash_sale',
  },
]
