import type { VoucherPreset } from '../types/coupon'

export const CAMBODIA_COUPON_PRESETS: VoucherPreset[] = [
  {
    id: 'welcome_new_shopper',
    nameKm: '🎁 ប័ណ្ណស្វាគមន៍អតិថិជនថ្មី ($3.00 OFF)',
    nameEn: 'New Shopper Welcome $3 Voucher',
    badge: 'WELCOME $3',
    codePrefix: 'WELCOME3',
    type: 'fixed',
    value: 3,
    currency: 'USD',
    minimum_amount: 15,
    minimum_amount_khr: 60000,
    channel_scope: 'all',
    payment_methods: ['all'],
    customer_target_type: 'new_customer_only',
    usage_limit: 1000,
    per_customer_limit: 1,
    descriptionKm: 'បញ្ចុះតម្លៃ $3.00 (១២,០០០ ៛) លើការបញ្ជាទិញលើកដំបូងចាប់ពី $15 ឡើងទៅ',
    descriptionEn: 'Save $3.00 on first-time customer purchase over $15 across web and in-store POS',
  },
  {
    id: 'bakong_khqr_voucher',
    nameKm: '🇰🇭 ប័ណ្ណស្កេនទូទាត់ Bakong KHQR (8,000 ៛ / $2 OFF)',
    nameEn: 'Bakong KHQR 8,000 KHR / $2 Voucher',
    badge: 'KHQR 8000៛',
    codePrefix: 'KHQR2',
    type: 'fixed',
    value: 2,
    currency: 'USD',
    minimum_amount: 10,
    minimum_amount_khr: 40000,
    channel_scope: 'all',
    payment_methods: ['khqr_bakong'],
    customer_target_type: 'all',
    usage_limit: 800,
    per_customer_limit: 2,
    descriptionKm: 'បញ្ចុះ $2.00 ឬ ៨,០០០ ៛ ពេលស្កេនទូទាត់តាម Bakong KHQR ចាប់ពី ៤០,០០០ ៛',
    descriptionEn: 'Save $2.00 (8,000 KHR) when paying via Bakong KHQR on min $10 purchase',
  },
  {
    id: 'free_delivery_voucher',
    nameKm: '🚚 ប័ណ្ណដឹកជញ្ជូនឥតគិតថ្លៃ ២៥ ខេត្ត-ក្រុង (Free Nationwide Delivery)',
    nameEn: 'Free Delivery Voucher Across Cambodia',
    badge: 'FREE DELIVERY',
    codePrefix: 'FREESHIP',
    type: 'free_shipping',
    value: 100,
    currency: 'USD',
    minimum_amount: 25,
    minimum_amount_khr: 100000,
    channel_scope: 'storefront_only',
    payment_methods: ['all'],
    customer_target_type: 'all',
    usage_limit: 1500,
    per_customer_limit: 5,
    descriptionKm: 'មិនគិតថ្លៃសេវាដឹកជញ្ជូនទូទាំងប្រទេសកម្ពុជា រាល់ការទិញចាប់ពី $25 ឡើងទៅលើ Website',
    descriptionEn: 'Free shipping on online orders over $25 to all 25 provinces in Cambodia',
  },
  {
    id: 'kny_gift_voucher',
    nameKm: '🌸 ប័ណ្ណកាដូពិធីបុណ្យចូលឆ្នាំខ្មែរ ($5.00 / 20,000 ៛)',
    nameEn: 'Khmer New Year $5 / 20,000 KHR Gift Voucher',
    badge: 'KNY $5 GIFT',
    codePrefix: 'KNYGIFT',
    type: 'fixed',
    value: 5,
    currency: 'USD',
    minimum_amount: 30,
    minimum_amount_khr: 120000,
    channel_scope: 'all',
    payment_methods: ['all'],
    customer_target_type: 'all',
    usage_limit: 500,
    per_customer_limit: 1,
    descriptionKm: 'ប័ណ្ណកាដូពិសេសសម្រាប់ឱកាសចូលឆ្នាំថ្មីប្រពៃណីខ្មែរ បញ្ចុះតម្លៃ $5.00 ឬ ២០,០០០ ៛',
    descriptionEn: 'Special gift card voucher for Khmer New Year celebration offering $5.00 discount',
  },
  {
    id: 'vip_secret_discount',
    nameKm: '💎 ប័ណ្ណ VIP Member Secret Discount (15% OFF, Cap $10)',
    nameEn: 'VIP Member Secret 15% OFF (Cap $10)',
    badge: 'VIP 15% OFF',
    codePrefix: 'VIP15',
    type: 'percentage',
    value: 15,
    max_discount_cap: 10,
    currency: 'USD',
    minimum_amount: 20,
    minimum_amount_khr: 80000,
    channel_scope: 'all',
    payment_methods: ['all'],
    customer_target_type: 'vip_tiers',
    usage_limit: 300,
    per_customer_limit: 1,
    descriptionKm: 'បញ្ចុះតម្លៃ ១៥% (រហូតដល់ $10) ផ្តាច់មុខសម្រាប់សមាជិក VIP Silver, Gold និង Platinum',
    descriptionEn: 'Exclusive 15% discount (up to $10 max) for VIP tier members',
  },
]
