import type { FlashSalePreset, TimeSlotSession } from '../types/flashSale'

export const FLASH_SALE_TIME_SESSIONS: TimeSlotSession[] = [
  {
    id: 'midnight_rush',
    labelKm: '🌙 ពាក់កណ្តាលអធ្រាត្រ (Midnight Madness)',
    labelEn: 'Midnight Madness (00:00 - 02:00)',
    timeRange: '00:00 - 02:00',
    startHour: 0,
    endHour: 2,
    iconName: 'Moon',
    badge: 'Night Deal',
  },
  {
    id: 'lunch_break',
    labelKm: '🍱 ម៉ោងបាយថ្ងៃត្រង់ (Lunch Rush Deals)',
    labelEn: 'Lunch Break Rush (12:00 - 14:00)',
    timeRange: '12:00 - 14:00',
    startHour: 12,
    endHour: 14,
    iconName: 'Sun',
    badge: 'Lunch Break',
  },
  {
    id: 'prime_evening',
    labelKm: '🔥 ម៉ោងមាសពេលល្ងាច (Prime Evening Rush)',
    labelEn: 'Prime Evening Rush (18:00 - 21:00)',
    timeRange: '18:00 - 21:00',
    startHour: 18,
    endHour: 21,
    iconName: 'Flame',
    badge: 'Hot Prime',
  },
  {
    id: 'last_call_night',
    labelKm: '⚡ នាទីចុងក្រោយ (Last Call Clearance)',
    labelEn: 'Last Call Night (21:00 - 23:59)',
    timeRange: '21:00 - 23:59',
    startHour: 21,
    endHour: 23,
    iconName: 'Zap',
    badge: 'Last Call',
  },
  {
    id: 'custom_session',
    labelKm: '⏱️ កំណត់ម៉ោងផ្ទាល់ខ្លួន (Custom Time Range)',
    labelEn: 'Custom 24H or Multi-day Range',
    timeRange: 'Custom',
    startHour: 0,
    endHour: 24,
    iconName: 'Clock',
    badge: 'Custom',
  },
]

export const CAMBODIA_FLASH_SALE_PRESETS: FlashSalePreset[] = [
  {
    id: 'kny_mega_flash',
    nameKm: '🌸 មហោស្រពចូលឆ្នាំខ្មែរ (Khmer New Year Flash 50% OFF)',
    nameEn: 'Khmer New Year Mega Flash Sale 50% OFF',
    badge: 'KNY 2026',
    category: 'Cambodia Festival',
    time_slot_name: 'Prime Evening Rush (18:00 - 21:00)',
    default_duration_hours: 3,
    channel_scope: 'all',
    discount_percent: 50,
    descriptionKm: 'លក់បញ្ចុះតម្លៃរហូតដល់ ៥០% សម្រាប់អបអរសាទរបុណ្យចូលឆ្នាំថ្មីប្រពៃណីជាតិខ្មែរ លើគ្រប់សាខា POS និង Storefront',
    descriptionEn: 'Massive 50% flash discount celebrating Khmer New Year across physical POS outlets and online storefront',
    quota_per_product: 50,
    per_customer_limit: 2,
  },
  {
    id: 'pchum_ben_rush',
    nameKm: '🏮 ពិធីបុណ្យភ្ជុំបិណ្ឌ (Pchum Ben Special Rush 35% OFF)',
    nameEn: 'Pchum Ben Family Rush 35% OFF',
    badge: 'PCHUM BEN',
    category: 'Cambodia Festival',
    time_slot_name: 'Lunch Break Rush (12:00 - 14:00)',
    default_duration_hours: 2,
    channel_scope: 'all',
    discount_percent: 35,
    descriptionKm: 'Flash Sale ពិសេសសម្រាប់រដូវកាលបុណ្យភ្ជុំបិណ្ឌ ទំនិញកាដូ និងគ្រឿងប្រើប្រាស់គ្រួសារ បញ្ចុះតម្លៃ ៣៥%',
    descriptionEn: 'Family gathering & gift sets 35% flash price during Pchum Ben holiday sessions',
    quota_per_product: 40,
    per_customer_limit: 3,
  },
  {
    id: 'water_festival_deal',
    nameKm: '🚣 ព្រះរាជពិធីបុណ្យអុំទូក (Water Festival Flash Rush)',
    nameEn: 'Water Festival Lightning Deals 40% OFF',
    badge: 'BON OM TOUK',
    category: 'Cambodia Festival',
    time_slot_name: 'Prime Evening Rush (18:00 - 21:00)',
    default_duration_hours: 4,
    channel_scope: 'all',
    discount_percent: 40,
    descriptionKm: 'ការបញ្ចុះតម្លៃ ៤០% អបអរព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អមជាមួយការស្កេន Bakong KHQR',
    descriptionEn: 'Fast flash sales 40% OFF during the Water Festival regatta celebrations with instant KHQR payment',
    quota_per_product: 60,
    per_customer_limit: 2,
  },
  {
    id: 'singles_day_1111',
    nameKm: '🛍️ មហាព្រឹត្តិការណ៍ 11.11 (11.11 Midnight Madness 60% OFF)',
    nameEn: '11.11 Global Mega Flash Sale 60% OFF',
    badge: '11.11 MEGA',
    category: 'Global Shopping Festival',
    time_slot_name: 'Midnight Madness (00:00 - 02:00)',
    default_duration_hours: 2,
    channel_scope: 'all',
    discount_percent: 60,
    descriptionKm: 'ព្រឹត្តិការណ៍ទិញទំនិញធំបំផុតប្រចាំឆ្នាំ 11.11 បញ្ចុះតម្លៃរហូតដល់ ៦០% ចាប់ពីម៉ោង 00:00 យប់',
    descriptionEn: 'Single\'s Day annual biggest flash drop up to 60% off during the midnight rush countdown',
    quota_per_product: 100,
    per_customer_limit: 1,
  },
  {
    id: 'grand_1212_rush',
    nameKm: '🎄 ពិធីបិទឆ្នាំ 12.12 (12.12 Grand Year-End Flash 45% OFF)',
    nameEn: '12.12 Grand Year-End Flash 45% OFF',
    badge: '12.12 FINALE',
    category: 'Global Shopping Festival',
    time_slot_name: 'Prime Evening Rush (18:00 - 21:00)',
    default_duration_hours: 3,
    channel_scope: 'all',
    discount_percent: 45,
    descriptionKm: 'Flash Sale បញ្ចុះតម្លៃ ៤៥% សម្រាប់កម្មវិធីទិញទំនិញចុងឆ្នាំ 12.12 ទូទាំងប្រទេស',
    descriptionEn: 'Year-end inventory booster 45% flash promotion for holiday shoppers',
    quota_per_product: 80,
    per_customer_limit: 2,
  },
  {
    id: 'payday_weekend',
    nameKm: '💳 ចុងសប្តាហ៍បើកប្រាក់ខែ (Payday Weekend Flash Deals)',
    nameEn: 'Payday Weekend Rush 30% OFF',
    badge: 'PAYDAY DEALS',
    category: 'Monthly Routine',
    time_slot_name: 'Lunch Break Rush (12:00 - 14:00)',
    default_duration_hours: 48,
    channel_scope: 'all',
    discount_percent: 30,
    descriptionKm: 'ការបញ្ចុះតម្លៃ ៣០% រៀងរាល់ចុងសប្តាហ៍ចុងខែ បង្កើនការលក់ទាំងលើ POS និង Website',
    descriptionEn: 'Boost month-end pay-slip conversions with 30% flash discounts across all retail branches',
    quota_per_product: 50,
    per_customer_limit: 3,
  },
  {
    id: 'tech_gadgets_lightning',
    nameKm: '⚡ បច្ចេកវិទ្យា & គ្រឿងអេឡិចត្រូនិច (Tech Flash Deals 25% OFF)',
    nameEn: 'Electronics Lightning Deals 25% OFF',
    badge: 'TECH FLASH',
    category: 'Electronics',
    time_slot_name: 'Midnight Madness (00:00 - 02:00)',
    default_duration_hours: 2,
    channel_scope: 'storefront_only',
    discount_percent: 25,
    descriptionKm: 'Flash Sale សម្រាប់តែស្មាតហ្វូន កាសស្តាប់ និងគ្រឿង accessories បច្ចេកវិទ្យា',
    descriptionEn: 'Storefront exclusive lightning deal on consumer electronics, audio gear, and peripherals',
    quota_per_product: 25,
    per_customer_limit: 1,
  },
]
