import type { CampaignPreset } from '../types/promotion'

export const CAMBODIA_CAMPAIGN_PRESETS: CampaignPreset[] = [
  {
    id: 'kny_super_sale',
    nameKm: '🌸 មហោស្រពចូលឆ្នាំខ្មែរ (Khmer New Year Mega Promo)',
    nameEn: 'Khmer New Year Mega Promo 15% OFF',
    badge: 'KNY 2026',
    category: 'Festival',
    type: 'percentage',
    channel_scope: 'all',
    descriptionKm: 'បញ្ចុះតម្លៃ ១៥% (រហូតដល់ $15) រាល់ការទិញចាប់ពី $30 ឡើងទៅ លើគ្រប់បណ្តាញលក់',
    descriptionEn: 'Get 15% OFF (up to $15 max) on minimum $30 spend across POS and Storefront',
    conditions: {
      min_spend_usd: 30,
      min_spend_khr: 120000,
      payment_methods: ['all'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'percentage',
      discount_value: 15,
      max_discount_cap: 15,
      currency: 'USD',
    },
    priority: 10,
    is_stackable: true,
    total_budget_cap: 2500,
    max_redemptions: 500,
    per_customer_limit: 2,
  },
  {
    id: 'bakong_khqr_cashback',
    nameKm: '🇰🇭 ស្កេនទូទាត់តាម Bakong KHQR បញ្ចុះតម្លៃ ៥%',
    nameEn: 'Bakong KHQR 5% Instant Discount',
    badge: 'KHQR ONLY',
    category: 'Payment Method',
    type: 'percentage',
    channel_scope: 'all',
    descriptionKm: 'ទទួលបានការបញ្ចុះតម្លៃបន្ថែម ៥% (រហូតដល់ $3) រាល់ការស្កេនទូទាត់តាម Bakong KHQR ចាប់ពី $15',
    descriptionEn: 'Save extra 5% (up to $3) when paying with Bakong KHQR on minimum $15 purchase',
    conditions: {
      min_spend_usd: 15,
      min_spend_khr: 60000,
      payment_methods: ['khqr_bakong'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'percentage',
      discount_value: 5,
      max_discount_cap: 3,
      currency: 'USD',
    },
    priority: 8,
    is_stackable: true,
    total_budget_cap: 1000,
    max_redemptions: 1000,
    per_customer_limit: 3,
  },
  {
    id: 'pchum_ben_bogo',
    nameKm: '🏮 ប្រូម៉ូសិនភ្ជុំបិណ្ឌ ទិញ ២ ថែម ១ (Pchum Ben BOGO)',
    nameEn: 'Pchum Ben Family BOGO (Buy 2 Get 1 Free)',
    badge: 'BOGO COMBO',
    category: 'Festival',
    type: 'bogo',
    channel_scope: 'all',
    descriptionKm: 'ទិញទំនិញប្រភេទអាហារ/ភេសជ្ជៈ ឬកាដូ ២ ឯកតា ថែមជូន ១ ឯកតាឥតគិតថ្លៃ',
    descriptionEn: 'Buy any 2 qualifying items in category and get 1 free item',
    conditions: {
      buy_quantity: 2,
      get_quantity: 1,
      payment_methods: ['all'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'bogo',
      discount_value: 100,
    },
    priority: 6,
    is_stackable: false,
    total_budget_cap: 1500,
    max_redemptions: 300,
    per_customer_limit: 1,
  },
  {
    id: 'water_festival_deal',
    nameKm: '🚣 ព្រះរាជពិធីបុណ្យអុំទូក បញ្ចុះ $5 ភ្លាមៗ',
    nameEn: 'Water Festival Flat $5 OFF',
    badge: 'BON OM TOUK',
    category: 'Festival',
    type: 'fixed_amount',
    channel_scope: 'all',
    descriptionKm: 'បញ្ចុះតម្លៃ $5.00 ឬ 20,000៛ ភ្លាមៗ ពេលជាវអស់ចាប់ពី $25 ឡើងទៅ',
    descriptionEn: 'Enjoy flat $5.00 discount on cart total over $25.00',
    conditions: {
      min_spend_usd: 25,
      min_spend_khr: 100000,
      payment_methods: ['all'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'fixed_amount',
      discount_value: 5,
      currency: 'USD',
    },
    priority: 7,
    is_stackable: false,
    total_budget_cap: 2000,
    max_redemptions: 400,
    per_customer_limit: 1,
  },
  {
    id: 'double_digit_mega',
    nameKm: '⚡ មហាសន្សំ 11.11 / 12.12 Mega Sale Day',
    nameEn: 'Mega Double-Digit 20% OFF + Free Shipping',
    badge: 'MEGA SALE',
    category: 'Mega Event',
    type: 'percentage',
    channel_scope: 'all',
    descriptionKm: 'បញ្ចុះតម្លៃ ២០% (រហូតដល់ $20) សម្រាប់ការទិញចាប់ពី $40 ឡើងទៅ',
    descriptionEn: 'Massive 20% discount (up to $20) for minimum $40 spend',
    conditions: {
      min_spend_usd: 40,
      min_spend_khr: 160000,
      payment_methods: ['all'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'percentage',
      discount_value: 20,
      max_discount_cap: 20,
      currency: 'USD',
    },
    priority: 9,
    is_stackable: true,
    total_budget_cap: 5000,
    max_redemptions: 600,
    per_customer_limit: 1,
  },
  {
    id: 'free_nationwide_shipping',
    nameKm: '🚚 ដឹកជញ្ជូនឥតគិតថ្លៃ ២៥ ខេត្ត-ក្រុង (Free Nationwide Delivery)',
    nameEn: 'Free Nationwide Shipping Orders $35+',
    badge: 'FREE DELIVERY',
    category: 'Shipping',
    type: 'free_shipping',
    channel_scope: 'storefront_only',
    descriptionKm: 'មិនគិតថ្លៃសេវាដឹកជញ្ជូនទូទាំងប្រទេសកម្ពុជា រាល់ការបញ្ជាទិញចាប់ពី $35 ឡើងទៅលើ Website',
    descriptionEn: 'Free delivery across all 25 provinces in Cambodia on web orders above $35',
    conditions: {
      min_spend_usd: 35,
      min_spend_khr: 140000,
      payment_methods: ['all'],
      customer_groups: ['all'],
      branch_ids: 'all',
    },
    rewards: {
      discount_type: 'free_shipping',
      discount_value: 100,
    },
    priority: 5,
    is_stackable: true,
    total_budget_cap: 3000,
    max_redemptions: 1500,
    per_customer_limit: 10,
  },
]
